#!/usr/bin/env node
// Apply setup payload: config + PRODUCT.md + DESIGN.md, then bootstrap and check.
// Usage: apply-setup.mjs [--file path.json]   (stdin if --file omitted)

import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { spawnSync } from 'node:child_process'
import { join } from 'node:path'

const root = process.cwd()
const fileFlag = process.argv.indexOf('--file')
const input = fileFlag !== -1
  ? readFileSync(process.argv[fileFlag + 1], 'utf8')
  : readFileSync(0, 'utf8')

let payload
try {
  payload = JSON.parse(input)
} catch (e) {
  console.error('Invalid JSON payload:', e.message)
  process.exit(1)
}

const { config, productMarkdown, designMarkdown } = payload
if (!config?.department?.name || !config?.service?.name) {
  console.error('Payload must include config.department and config.service.name')
  process.exit(1)
}
if (!productMarkdown || !designMarkdown) {
  console.error('Payload must include productMarkdown and designMarkdown')
  process.exit(1)
}

const configDoc = {
  _comment: 'Generated by gov-prototype-setup. Re-run setup via chat or edit by hand, then node scripts/sync-context.mjs if bootstrap already ran.',
  department: config.department,
  service: config.service,
  standards: config.standards ?? {
    govukFrontendVersion: '6.x',
    styleGuideUrl: 'https://github.com/DEFRA/aice-team/blob/main/documentation/style-guides/javascript.md',
    wcagTarget: '2.2 AA'
  },
  mcp: config.mcp ?? { figma: 'Figma', research: 'Notion', docs: 'Notion' },
  figma: config.figma ?? {
    verifiedAccount: '',
    planKey: '',
    planName: '',
    projectId: '',
    projectName: '',
    primaryFileUrl: '',
    primaryFileKey: ''
  }
}

writeFileSync(
  join(root, 'config', 'project.json'),
  JSON.stringify(configDoc, null, 2) + '\n',
  'utf8'
)
writeFileSync(join(root, 'PRODUCT.md'), productMarkdown.trim() + '\n', 'utf8')
writeFileSync(join(root, 'DESIGN.md'), designMarkdown.trim() + '\n', 'utf8')

console.log('Wrote config/project.json, PRODUCT.md, DESIGN.md')

const run = (script, args = []) => {
  const r = spawnSync('node', [join(root, script), ...args], {
    cwd: root,
    stdio: 'inherit',
    encoding: 'utf8'
  })
  return r.status ?? 1
}

const bootstrapStatus = run('scripts/bootstrap.mjs')
if (bootstrapStatus !== 0) process.exit(bootstrapStatus)

const syncStatus = run('scripts/sync-context.mjs')
if (syncStatus !== 0) process.exit(syncStatus)

const setupStatus = run('scripts/check-setup.mjs')
if (setupStatus !== 0) process.exit(setupStatus)

const govukInstalled = join(root, 'node_modules', 'govuk-frontend', 'package.json')
if (existsSync(govukInstalled)) {
  const govukStatus = run('scripts/check-govuk-frontend.mjs')
  if (govukStatus === 1) {
    console.warn(
      'Note: a newer govuk-frontend is on npm — run npm run check:govuk-frontend after setup and see docs/standards/govuk-frontend.md'
    )
  } else if (govukStatus === 2) {
    console.warn('Could not verify govuk-frontend — run npm run check:govuk-frontend after npm install')
  }
}

process.exit(0)
